# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class AxisOrder(str, Enum):
    """
    AxisOrder
    """

    """
    allowed enum values
    """
    NORTHEAST = 'northEast'
    EASTNORTH = 'eastNorth'

    @classmethod
    def from_json(cls, json_str: str) -> AxisOrder:
        """Create an instance of AxisOrder from a JSON string"""
        return AxisOrder(json.loads(json_str))


