# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.date_time_parse_format import DateTimeParseFormat

class CustomOgrSourceTimeFormat(BaseModel):
    """
    CustomOgrSourceTimeFormat
    """
    custom_format: DateTimeParseFormat = Field(..., alias="customFormat")
    format: StrictStr = Field(...)
    __properties = ["customFormat", "format"]

    @validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('custom'):
            raise ValueError("must be one of enum values ('custom')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CustomOgrSourceTimeFormat:
        """Create an instance of CustomOgrSourceTimeFormat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of custom_format
        if self.custom_format:
            _dict['customFormat'] = self.custom_format.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CustomOgrSourceTimeFormat:
        """Create an instance of CustomOgrSourceTimeFormat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CustomOgrSourceTimeFormat.parse_obj(obj)

        _obj = CustomOgrSourceTimeFormat.parse_obj({
            "custom_format": DateTimeParseFormat.from_dict(obj.get("customFormat")) if obj.get("customFormat") is not None else None,
            "format": obj.get("format")
        })
        return _obj


