# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FeatureDataType(str, Enum):
    """
    FeatureDataType
    """

    """
    allowed enum values
    """
    CATEGORY = 'category'
    INT = 'int'
    FLOAT = 'float'
    TEXT = 'text'
    BOOL = 'bool'
    DATETIME = 'dateTime'

    @classmethod
    def from_json(cls, json_str: str) -> FeatureDataType:
        """Create an instance of FeatureDataType from a JSON string"""
        return FeatureDataType(json.loads(json_str))


