# coding: utf-8

"""
    Geo Engine API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FeatureType(str, Enum):
    """
    FeatureType
    """

    """
    allowed enum values
    """
    POINT = 'Point'
    MULITPOINT = 'MulitPoint'
    LINESTRING = 'LineString'
    MULTILINESTRING = 'MultiLineString'
    POLYGON = 'Polygon'
    MULTIPOLYGON = 'MultiPolygon'

    @classmethod
    def from_json(cls, json_str: str) -> FeatureType:
        """Create an instance of FeatureType from a JSON string"""
        return FeatureType(json.loads(json_str))


