# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, conint
from openapi_client.models.gdal_dataset_parameters import GdalDatasetParameters
from openapi_client.models.time_interval import TimeInterval

class GdalLoadingInfoTemporalSlice(BaseModel):
    """
    one temporal slice of the dataset that requires reading from exactly one Gdal dataset
    """
    cache_ttl: Optional[conint(strict=True, ge=0)] = Field(None, alias="cacheTtl")
    params: Optional[GdalDatasetParameters] = None
    time: TimeInterval = Field(...)
    __properties = ["cacheTtl", "params", "time"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GdalLoadingInfoTemporalSlice:
        """Create an instance of GdalLoadingInfoTemporalSlice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of params
        if self.params:
            _dict['params'] = self.params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of time
        if self.time:
            _dict['time'] = self.time.to_dict()
        # set to None if params (nullable) is None
        # and __fields_set__ contains the field
        if self.params is None and "params" in self.__fields_set__:
            _dict['params'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GdalLoadingInfoTemporalSlice:
        """Create an instance of GdalLoadingInfoTemporalSlice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GdalLoadingInfoTemporalSlice.parse_obj(obj)

        _obj = GdalLoadingInfoTemporalSlice.parse_obj({
            "cache_ttl": obj.get("cacheTtl"),
            "params": GdalDatasetParameters.from_dict(obj.get("params")) if obj.get("params") is not None else None,
            "time": TimeInterval.from_dict(obj.get("time")) if obj.get("time") is not None else None
        })
        return _obj


