# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator
from openapi_client.models.colorizer import Colorizer

class RasterSymbologyWithType(BaseModel):
    """
    RasterSymbologyWithType
    """
    colorizer: Colorizer = Field(...)
    opacity: Union[StrictFloat, StrictInt] = Field(...)
    type: StrictStr = Field(...)
    __properties = ["colorizer", "opacity", "type"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('raster'):
            raise ValueError("must be one of enum values ('raster')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RasterSymbologyWithType:
        """Create an instance of RasterSymbologyWithType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of colorizer
        if self.colorizer:
            _dict['colorizer'] = self.colorizer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RasterSymbologyWithType:
        """Create an instance of RasterSymbologyWithType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RasterSymbologyWithType.parse_obj(obj)

        _obj = RasterSymbologyWithType.parse_obj({
            "colorizer": Colorizer.from_dict(obj.get("colorizer")) if obj.get("colorizer") is not None else None,
            "opacity": obj.get("opacity"),
            "type": obj.get("type")
        })
        return _obj


