# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, validator

class TaskStatusWithId(BaseModel):
    """
    TaskStatusWithId
    """
    estimated_time_remaining: Optional[StrictStr] = Field(None, alias="estimatedTimeRemaining")
    info: Optional[Dict[str, Any]] = None
    pct_complete: Optional[StrictStr] = Field(None, alias="pctComplete")
    status: Optional[StrictStr] = None
    time_started: Optional[StrictStr] = Field(None, alias="timeStarted")
    time_total: Optional[StrictStr] = Field(None, alias="timeTotal")
    clean_up: Optional[Dict[str, Any]] = Field(None, alias="cleanUp")
    error: Optional[Dict[str, Any]] = None
    task_id: StrictStr = Field(..., alias="taskId")
    __properties = ["estimatedTimeRemaining", "info", "pctComplete", "status", "timeStarted", "timeTotal", "cleanUp", "error", "taskId"]

    @validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('failed'):
            raise ValueError("must be one of enum values ('failed')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskStatusWithId:
        """Create an instance of TaskStatusWithId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskStatusWithId:
        """Create an instance of TaskStatusWithId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaskStatusWithId.parse_obj(obj)

        _obj = TaskStatusWithId.parse_obj({
            "estimated_time_remaining": obj.get("estimatedTimeRemaining"),
            "info": obj.get("info"),
            "pct_complete": obj.get("pctComplete"),
            "status": obj.get("status"),
            "time_started": obj.get("timeStarted"),
            "time_total": obj.get("timeTotal"),
            "clean_up": obj.get("cleanUp"),
            "error": obj.get("error"),
            "task_id": obj.get("taskId")
        })
        return _obj


