# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class TypedGeometryOneOf(BaseModel):
    """
    TypedGeometryOneOf
    """
    data: Optional[Any] = Field(..., alias="Data")
    __properties = ["Data"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TypedGeometryOneOf:
        """Create an instance of TypedGeometryOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if data (nullable) is None
        # and __fields_set__ contains the field
        if self.data is None and "data" in self.__fields_set__:
            _dict['Data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TypedGeometryOneOf:
        """Create an instance of TypedGeometryOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TypedGeometryOneOf.parse_obj(obj)

        _obj = TypedGeometryOneOf.parse_obj({
            "data": obj.get("Data")
        })
        return _obj


