# coding: utf-8

"""
    Geo Engine Pro API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.7.0
    Contact: dev@geoengine.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class WmsVersion(str, Enum):
    """
    WmsVersion
    """

    """
    allowed enum values
    """
    ENUM_1_DOT_3_DOT_0 = '1.3.0'

    @classmethod
    def from_json(cls, json_str: str) -> WmsVersion:
        """Create an instance of WmsVersion from a JSON string"""
        return WmsVersion(json.loads(json_str))


